collections:
  chapters:
    output: true
    permalink: /chapters/:title/
  characters:
    output: true
    permalink: /characters/:title/
collections:
  news:
    output: true
    permalink: /news/:title/
