# Site settings
title: "Kyuukei"
email: "saiminator@kyuukei.com"
description: "Kyuu’s Breaktime Stories"
baseurl: ""  # the subpath of your site, e.g. /blog, or empty for root
url: "https://Kyuukei.com"  # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
permalink: pretty

# Collections
collections:
  chapters:
    output: true
    permalink: "/stories/:story_segment/chapter-:chapter_number/"
  characters:
    output: true
    permalink: "/characters/:title/"
  news:
    output: true
    permalink: "/news/:title/"
  questions:
    output: true
    permalink: "/questions/:title/"
  stories:
    output: true
    permalink: "/stories/:slug/"


# Plugins (if you use any)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
